# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15.6

      # Service container image
      - image: redis:6.0.6-alpine
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      #- run: sudo apt-get install redis-tools ; while ! redis-cli ping 2>/dev/null ; do sleep 1 ; done
      - run: go get -v -t -d ./...
      - run: go test -v ./... -cover -coverprofile /tmp/cover.out
      - run: go tool cover -html /tmp/cover.out -o /tmp/coverage.html

      - store_artifacts:
          path: /tmp/coverage.html
          destination: coverage.html

      - store_artifacts:
          path: /tmp/coverage.html
          destination: coverage.html
